### ISSUE TITLE
你好 想问下这个项目的数据可以提供下吗？

### ISSUE THREAD

**Issue by xiaoerlaigeid** [Imanity/3d_2d_registration#1]
我想在这个基础上做一些改进 正在学习 一下，请问有什么建议吗。 还有就是没有看到数据想问下有数据提供吗？

**Comment by Imanity** [comment]
你好，这个用的数据是联系的医院给的数据orz应该不能公开。。相关资料的话可以google scholar搜registration/alignment并加上2d/3d之类修饰

**Comment by xiaoerlaigeid** [comment]
谢谢回复！非常感谢
想问下你是参考的那篇论文做的这个呢？ 就是这个大体思路是什么样的呢？ 因为我看到你好像是一层层配准感觉和那种直接从3d投影到2d做优化好像不太一样，就比较好奇
还有就是我看到你两个模态数据格式是什么样的呢？
看到das里面有一些其他的参数，请问这个格式是你自己定义的还是从dsa里面取出来就是这个格式的呢？  
还有你三维的体素数据是vol 这个是从ct里面取出来就是这个格式吗？ 不应该是dicom格式吗？

**Comment by Imanity** [comment]
orz这个就瞎做的。。。就是直接投影完算个误差。。然后拿优化器优化误差。。很水的
数据格式都是dicom。。读成数组
读dsa我记得是直接github上直接找开源代码改的（
三维的。。那个是别的地方转成vol格式读的。。读三维dicom的代码是实验室其他同学写的不能开源orz。。如果是简单的dicom三维数据的话用vtk自带的库函数就能读。或者转成nifti读也可以

**Comment by xiaoerlaigeid** [comment]
十分感谢！
